### ISSUE TITLE
dataset link to google drive is null

### ISSUE THREAD

**Issue by ZhangxinruBIT** [ahmedgh970/Transformers_Unsupervised_Anomaly_Segmentation#1]
Hi@ahmedgh970, thank you for sharing your code.
I have trouble with access to your dataset through given link to google drive. (https://drive.google.com/file/d/11Bj7ATQtxLt7PyL3fqyyeXqNNrRqgS9K/view?usp=sharing) Please check, thank you.

Cheers!

**Comment by ahmedgh970** [comment]
Hello Xinru,
Here is the link:
https://drive.google.com/file/d/1C7gKuSz1an9g5ZezNS3ziuRogg-EAQrW/view?usp=sharing
Hope it helps !
Best,
Ahmed.

**Comment by ZhangxinruBIT** [comment]
Ok, thank you for reply. However, I have another question about binary segmentation.  It seems that the final result is residual (float32, 0~1) but I have no idea to acquire the binary segmentation. Is there any advised threshold or extreme operation? And in [DCAE.py](https://github.com/ahmedgh970/Transformers_Unsupervised_Anomaly_Segmentation/blob/138a68f64579d8f2ef33f8c3007d2c7cb9b645c6/models/Autoencoders/DCAE.py) , line 202
```py
#-- Evaluation

print('\nEvaluate =========>\n')        
[AUROC, AUPRC, AVG_DICE, MAD, STD], DICE = eval_residuals(my_labels, residual)     
results = (f'\nResults after median_filter :\n - AUROC = {AUROC}\n - AUPRC = {AUPRC}\n - AVG_DICE = {AVG_DICE}\n - MEDIAN_ABSOLUTE_DEVIATION = {MAD}\n - STANDARD_DEVIATION = {STD}')
print(results)
```
the DICE is caculated by true labels and residual, not the hard dice?

Thanks, looking forward to your reply!

**Comment by ahmedgh970** [comment]
Dear Xinru,

The paper is still under review in another MICCAI workshop, so i can't give a public link.

To answer your first question, we post-process the residual r ([0, 1], float32) to obtain the binary segmentation m by applying a 2D median filter F (kernel=5), and then applying squashing operator S to squash the 1% lower intensities, as described in this equation ==> m = S 1% (F k=5 (max(r, 0))).
For more details, read the calculate_residual(x, x_rec, x_prior) function in ./scripts/utils.py

We empirically determined the thresholds for each test-set as the best ones that maximize the evaluation results. But there are plenty of works on how to choose the threshold for binary segmentation according to your test-set.

The Dice Coefficient (or F1 Score) was calculated between labels and the post-processed residual which is the binary mask m.  

Hope I answered your questions and feel free to ask me on my email address (ahmed.ghorbel888@gmail.com), if there is no issues with the repo.

Best.

**Comment by ahmedgh970** [comment]
Issue closed due to inactivity !
