### ISSUE TITLE
How to find the data?

### ISSUE THREAD

**Issue by hq-deng** [ahmedgh970/Transformers_Unsupervised_Anomaly_Segmentation#3]
Congratulations for your work. I'm trying to reproduce this work but I cannot find the drive files follow the data.txt, could you please check it?

**Comment by ahmedgh970** [comment]
Thank you. 
I removed the drive link due to the privacy agreement.
You can find all the datasets with a quick search on the net. I only saved this link https://www.oasis-brains.org/
Good luck !

**Comment by DreamInvoker** [comment]
Wonderful work! I want to ask more questions about the OASIS dataset. We could obtain  OASIS-3 from this [repo](https://github.com/NrgXnat/oasis-scripts). 

1. Did you run all scripts in this repo? If we need to reproduce your work, how to correctly download the needed data?
2. Where did you find <input_file.csv>? (or could you please provide this file for reproducing your work?)
3.  In this [link](https://github.com/ahmedgh970/Transformers_Unsupervised_Anomaly_Segmentation/blob/main/data/data.txt), do we need to further process the raw data for training or test set? Do you code actually use the raw data to reproduce your results?

Thank you so much in advance!
